### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by shaolyy** [zhouxianchen/robustGAT#1]
https://github.com/zhouxianchen/robustGAT/blob/5aec2aef01ca6e3409dabb93c4afa41b09043391/DeepRobust/deeprobust/graph/defense/__init__.py#L5 Did MyRo_GCN forget to upload?

**Comment by zhouxianchen** [comment]
I am sorry, Actually .MyRo_GCN is useless in this project, you can delete the code in the __init__.py.

**Comment by zhouxianchen** [comment]
We update the file and revise the __init__.py

**Comment by shaoyf9** [comment]
https://github.com/zhouxianchen/robustGAT/blob/c4466ee260c2e8347417035849615d9e07af736d/RoGAT/train.py#L15
Maybe this file also needs to be updated?

**Comment by shaolyy** [comment]
https://github.com/zhouxianchen/robustGAT/blob/c4466ee260c2e8347417035849615d9e07af736d/RoGAT/train.py#L15
Maybe this file also needs to be updated?

**Comment by zhouxianchen** [comment]
Thank you! We have updated the file train.py and make sure our program can be executed correctly.

**Comment by shaolyy** [comment]
Thank you for your help and patience patience！
